# Generated by Django 3.2.8 on 2021-10-06 09:10
import requests

from django.db import migrations, models


def add_data(apps, schema_editor):
    url = 'https://cars.mycar.kz/api/publications/?limit=120%20%20&ordering=-car_details__year_manufactured&city_id=&city_id_in=&mark_name=&model_name=&is_new_car=&has_credit=&is_prime=&min_year=2019&max_year=2020&max_mileage=&min_price=&max_price=&last_publication_id=1893'

    response = requests.get(url=url)
    response.raise_for_status()
    car_list_model = apps.get_model('car_list', 'CarList')
    for data in response.json()['results']:
        try:
            car_list_model.objects.create(
                car_model=data['car_model_name'],
                mark=data['car_mark_name'],
                price=int(float(data['price'])),
                mileage=int(data['mileage']),
                year_manufactured=int(data['year_manufactured'])
            )

        except:
            print(data)


class Migration(migrations.Migration):

    dependencies = [
        ('car_list', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_data),
    ]
